// Code generated by protoc-gen-comet v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated comet stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-comet v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	//"context"

	"github.com/cyruslo/library/pkg/net/comet"
	//"github.com/golang/protobuf/proto"
)

// DemoCometServer is the server API for Demo service.
type DemoCometServer interface {
	SetCometChan(cl *comet.ChanList, cs *comet.Server)
}

func RegisterDemoCometServer(s *comet.Server, srv DemoCometServer) {
	chanList := s.RegisterService(&_Comet_Demo_serviceDesc, srv)
	srv.SetCometChan(chanList, s)
}

var _Comet_Demo_serviceDesc = comet.ServiceDesc{
	ServiceName: "demo.service.v1.Demo",
	HandlerType: (*DemoCometServer)(nil),
	Methods:     []comet.MethodDesc{},
}
